complete app
SoftwareDefinedBuildings/mortar-analytics pull request #4
Opened 2019-03-19 05:08 UTC by phgupta

Completed energy baselines app.

2019-03-19 05:33 UTC, gtfierro requested changes

2019-03-19 05:33 UTC, gtfierro commented on energy_baselines/requirements.txt
> +googleapis-common-protos==1.5.8
I believe quite a few of these are just `pymortar`'s requirements, and aren't generally used. Can you remove the `pymortar` requirements to that those are more flexible to change? I think you can just have scipy, sklearn, scikit-learn, pymortar and pandas.

2019-03-19 05:50 UTC, phgupta commented
Removed the pymortar's requirements.

2019-03-19 07:01 UTC, gtfierro commented
Great! 

I was thinking given how many energy baseline apps we are going to have, do you mind moving your files into an application directory within a more general "energy_baselines" directory? I think this might help with organization, but let me know what you think

2019-03-19 19:18 UTC, phgupta commented
Yes, you're right. I named the application directory "baselines" in the event that we add other types of baselines like power/occupancy baselines.

2019-03-20 01:25 UTC, gtfierro commented
Great, thanks!

2019-03-20 01:25 UTC, gtfierro approved these changes

2019-03-20 01:25 UTC, merged